### ISSUE TITLE
16进制的整数转成十进制整数的时候符号的问题

### ISSUE THREAD

**Issue by neway3000** [dotnet/dotnet-api-docs.zh-cn#1]
原始16进制数：0xc4ada06ec4000    我想要的结果应该是：3460000000000000

Console.WriteLine(BigInteger.Parse("c4ada06ec4000", NumberStyles.HexNumber).ToString())
输出：-1043599627370496

Console.WriteLine(BigInteger.Parse("0000c4ada06ec4000", NumberStyles.HexNumber).ToString())
输出：3460000000000000

我发现字母开头的是就反过来变成负数，例如：F = -1 ;  E=-2 ; D = -3
在使用Parse的时候只要前面补0就变成正数，例如： 0F = 15 ;  0E = 14

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 523f53bd-05ef-41e0-0e1d-6c0f3fd2c3d7
* Version Independent ID: 5a963441-ebb8-738f-89b4-bda542e10268
* Content: [BigInteger.Parse Method (System.Numerics)](https://docs.microsoft.com/zh-cn/dotnet/api/system.numerics.biginteger.parse?redirectedfrom=MSDN&view=netframework-4.7.2#System_Numerics_BigInteger_Parse_System_String_System_Globalization_NumberStyles_)
* Content Source: [xml/System.Numerics/BigInteger.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Numerics/BigInteger.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@neway3000 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
@neway3000 文档里说了这件事啊
> 分析十六进制字符串时BigInteger.Parse(String, NumberStyles)和BigInteger.Parse(String, NumberStyles, IFormatProvider)方法假定，如果在字符串中的第一个字节的最高有效位设置，或如果字符串的第一个十六进制数字表示较低的四位的字节值，该值为使用 2 的补数表示形式来表示。 例如，"FF01"和"F01"表示的十进制值-255。 若要区分正负值，正值应包含前导零。
