### ISSUE TITLE
Too much strange translation, need a redo totally

### ISSUE THREAD

**Issue by MetallicPickaxe** [dotnet/dotnet-api-docs.zh-cn#13]
can not read clearly anymore

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 33f9cc30-f90e-fdc4-5b9e-00c5018e8348
* Version Independent ID: 28db996d-f438-e97d-ea1e-bccdeab8d7dd
* Content: [BigInteger Struct (System.Numerics)](https://docs.microsoft.com/zh-cn/dotnet/api/system.numerics.biginteger?view=netframework-4.7.2)
* Content Source: [xml/System.Numerics/BigInteger.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Numerics/BigInteger.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @MetallicPickaxe 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team
