### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by tanghuipang** [dotnet/dotnet-api-docs.zh-cn#15]
[在此处输入反馈]
The following code example demonstrates how to use Any to determine whether any element in a sequence satisfies a condition.
机器翻译的结果为:
下面的代码示例演示如何使用Any以确定是否序列中**的**任何元素**都**满足条件。
It means "The following code example demonstrates how to use Any to determine _all element in a sequence should satisfies a condition_."

此翻译是错误的，会严重误导用户。正确的翻译应该是:
下面的代码示例演示如何使用Any以确定是否序列中有任何元素能满足条件。

该文档中实际上把所有 “whether any element in a sequence satisfies a condition” 都翻译为 “是否序列中的任何元素都满足条件”, 而实际上都应该是 "是否序列中有任何元素能满足条件"。
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 028e83ab-7469-5a49-eb1e-fc733696bea3
* Version Independent ID: cbb14d50-ba7f-7f29-9535-43b936744bc4
* Content: [Enumerable.Any Method (System.Linq)](https://docs.microsoft.com/zh-cn/dotnet/api/system.linq.enumerable.any?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(System.Linq.Enumerable.Any%60%601);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv3.5);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @tanghuipang 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team
