### ISSUE TITLE
换而言之，由于一秒等于 1 亿个纳秒为单位

### ISSUE THREAD

**Issue by Epsilon2019** [dotnet/dotnet-api-docs.zh-cn#18]
"换而言之，由于一秒等于 1 亿个纳秒为单位"，billion应该翻译成10亿。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d7ab3146-450f-75e7-a64a-3531acb75675
* Version Independent ID: 4affdca4-8344-0b0f-ea71-173ca5b4a4f4
* Content: [Stopwatch.Frequency Field (System.Diagnostics)](https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.stopwatch.frequency?view=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics/Stopwatch.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Diagnostics/Stopwatch.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @Epsilon2019 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Epsilon2019

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.stopwatch.frequency?view=netframework-4.7.2  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
