### ISSUE TITLE
C#和VB中的各类方法的使用

### ISSUE THREAD

**Issue by YuhangDong** [dotnet/dotnet-api-docs.zh-cn#19]
希望代码示例稍微简单明了，不要太繁琐

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f1273030-375e-5f48-66ff-264f7a9646df
* Version Independent ID: 900db507-852d-8858-a186-949fe1e4baa3
* Content: [DateTimeFormatInfo.MonthNames Property (System.Globalization)](https://docs.microsoft.com/zh-cn/dotnet/api/system.globalization.datetimeformatinfo.monthnames?view=netframework-4.7.2)
* Content Source: [xml/System.Globalization/DateTimeFormatInfo.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Globalization/DateTimeFormatInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1583](https://github.com/dotnet/dotnet-api-docs/issues/1583) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@YuhangDong

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/dotnet-api-docs/issues/1583

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
