### ISSUE TITLE
[Suggestion]不说明一下是否线程安全？

### ISSUE THREAD

**Issue by ahdung** [dotnet/dotnet-api-docs.zh-cn#20]
不说明一下是否线程安全？老版本都有这个说明的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 62a87d45-f88a-6952-7efe-4178475b3f4b
* Version Independent ID: 5e331fc8-b855-b602-b47e-dc2e4e1b6a26
* Content: [Pen.Width Property (System.Drawing)](https://docs.microsoft.com/zh-cn/dotnet/api/system.drawing.pen.width?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Drawing/Pen.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Drawing/Pen.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2010](https://github.com/dotnet/dotnet-api-docs/issues/2010) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@ahdung

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/dotnet-api-docs/issues/2010

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team

**Comment by ahdung** [comment]
@CeciAc 谢谢你。
