### ISSUE TITLE
Platform Not Supported Exception

### ISSUE THREAD

**Issue by dzysdy** [dotnet/dotnet-api-docs.zh-cn#23]
I got an error "System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows" on Ubuntu system.
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fa765d00-19f8-74e4-4be1-1d7f1e7dc6ce
* Version Independent ID: 260749e3-69c6-a370-89b0-4f90d944fac7
* Content: [SerialPort Class (System.IO.Ports)](https://docs.microsoft.com/zh-cn/dotnet/api/system.io.ports.serialport?view=netcore-2.2)
* Content Source: [xml/System.IO.Ports/SerialPort.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.IO.Ports/SerialPort.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @dzysdy 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
