### ISSUE TITLE
Miss using to dispose stream

### ISSUE THREAD

**Issue by lixiaoqiang** [dotnet/dotnet-api-docs.zh-cn#24]
文档
https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Net/WebClient.xml
中的示例
~/samples/snippets/csharp/VS_Snippets_Remoting/NCLWebClientUserAgent/CS/useragent.cs#1

没有dispose掉WebClient OpenRead 生成的Stream以及WebClient本身。

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2232](https://github.com/dotnet/dotnet-api-docs/issues/2232) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@lixiaoqiang 

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/dotnet-api-docs/issues/2232

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
