### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Xieweikang123** [dotnet/dotnet-api-docs.zh-cn#26]
If New BoxSameDimensions().Equals(curBox, item) Then  在循环中生命对象是否会多消耗内存呢？在外面声明会不会更好？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fb4a647a-a595-38fc-826e-f6c95b754f6f
* Version Independent ID: d9a82967-6fd7-31b9-6fc9-377daa1a51d4
* Content: [ICollection&lt;T&gt; Interface (System.Collections.Generic)](https://docs.microsoft.com/zh-cn/dotnet/api/system.collections.generic.icollection-1?redirectedfrom=MSDN&view=netframework-4.8#feedback)
* Content Source: [xml/System.Collections.Generic/ICollection`1.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Collections.Generic/ICollection`1.xml)
* Product: **dotnet-api**
* Technology: **system.collections**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@Xieweikang123
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
