### ISSUE TITLE
11

### ISSUE THREAD

**Issue by huyongms** [dotnet/dotnet-api-docs.zh-cn#27]
1

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9a84c7f0-1d32-6177-8f67-7c58f03a4778
* Version Independent ID: 75d6f992-1c24-2ee0-724d-8a83f043640f
* Content: [SpinWait.Reset Method (System.Threading)](https://docs.microsoft.com/zh-cn/dotnet/api/system.threading.spinwait.reset?view=netframework-4.8#feedback)
* Content Source: [xml/System.Threading/SpinWait.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Threading/SpinWait.xml)
* Product: **dotnet-api**
* Technology: **system.threading**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by huyongms** [comment]
示例代码格式混乱

**Comment by CeciAc** [comment]
你好，@huyongms

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://docs.microsoft.com/zh-cn/dotnet/api/system.threading.spinwait.reset?view=netframework-4.8#feedback 。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
