### ISSUE TITLE
Xamarin.iOS < 10.8 cannot use this method ？

### ISSUE THREAD

**Issue by smilefacehh** [dotnet/dotnet-api-docs.zh-cn#28]
Xamarin.iOS &lt; 10.8 cannot use this method ？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 901859ec-d9e9-597e-90e1-12fbe29147cf
* Version Independent ID: b0def5ff-8c5c-036d-f305-12da3a6cc26e
* Content: [MethodBase.GetParameters Method (System.Reflection)](https://docs.microsoft.com/zh-cn/dotnet/api/system.reflection.methodbase.getparameters?view=netframework-1.1#feedback)
* Content Source: [xml/System.Reflection/MethodBase.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Reflection/MethodBase.xml)
* Product: **dotnet-api**
* Technology: **system.reflection**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @smilefacehh

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
