### ISSUE TITLE
about the name

### ISSUE THREAD

**Issue by wjkhappy14** [dotnet/dotnet-api-docs.zh-cn#29]
why named the RSACryptoServiceProvider as RSA?  RSA is a abstract  base class ,so ......
so this is a not good demo!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9500696a-6c08-90f8-0494-b4e5b1c79d7c
* Version Independent ID: ad68bc1f-4d84-1081-ff0b-419b6ca19d49
* Content: [RSACryptoServiceProvider Class (System.Security.Cryptography)](https://docs.microsoft.com/zh-cn/dotnet/api/system.security.cryptography.rsacryptoserviceprovider?view=netframework-4.8#feedback)
* Content Source: [xml/System.Security.Cryptography/RSACryptoServiceProvider.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Security.Cryptography/RSACryptoServiceProvider.xml)
* Product: **dotnet-api**
* Technology: **system.security**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @wjkhappy14 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
