### ISSUE TITLE
"AppDomain"未包含"CreateInstanceAndUnwrap"的定义

### ISSUE THREAD

**Issue by pygyme** [dotnet/dotnet-api-docs.zh-cn#30]
[在此处输入反馈]
下面这段代码，在VS2017  .Net Core 2.2下提示 `"AppDomain"未包含"CreateInstanceAndUnwrap"的定义`,
我使用示例代码，并未做任何修改，编译会通不过，编译错误
`CS1061	“AppDomain”未包含“CreateInstanceAndUnwrap”的定义，并且找不到可接受第一个“AppDomain”类型参数的可访问扩展方法“CreateInstanceAndUnwrap”`

```
PrimeNumberGenerator gen = (PrimeNumberGenerator) domain.CreateInstanceAndUnwrap(
                                            typeof(Example).Assembly.FullName,
                                            "PrimeNumberGenerator", true,
                                            BindingFlags.Default, null,
                                            new object[] { 1000000 }, null, null);
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f89232ef-e54d-8917-084f-8a881fb171c6
* Version Independent ID: de11f012-44a3-9727-93b9-d45b0a8fc479
* Content: [Exception Class (System)](https://docs.microsoft.com/zh-cn/dotnet/api/system.exception?view=netcore-2.2#feedback)
* Content Source: [xml/System/Exception.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System/Exception.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
<https://docs.microsoft.com/zh-cn/dotnet/api/system.appdomain.createinstanceandunwrap#适用于> 
2.2报错有什么问题么

**Comment by pygyme** [comment]
如果这个API `CreateInstanceAndUnwrap()` 只适用于.NET Framework 4.8,   那么请修改下面链接页面使用这个API的示例代码，
[https://docs.microsoft.com/zh-cn/dotnet/api/system.exception?view=netcore-2.2](https://docs.microsoft.com/zh-cn/dotnet/api/system.exception?view=netcore-2.2)

**Comment by CeciAc** [comment]
你好，@pygyme
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
