### ISSUE TITLE
Thread.Abort Method 不适用于 .NET Core

### ISSUE THREAD

**Issue by AFunnyKitty** [dotnet/dotnet-api-docs.zh-cn#32]
此页描述：
适用于
.NET Core
3.0 Preview 5 2.2 2.1 2.0
.NET Framework
4.8 4.7.2 4.7.1 4.7 4.6.2 4.6.1 4.6 4.5.2 4.5.1 4.5 4.0 3.5 3.0 2.0 1.1

这里给人误解哦，明明 .NETCore 不支持此方法

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9ad07e0b-045f-1883-6bbd-5f98dba08fcd
* Version Independent ID: 3764f95f-640e-b437-215a-b61cae9ec11e
* Content: [Thread.Abort Method (System.Threading)](https://docs.microsoft.com/zh-cn/dotnet/api/system.threading.thread.abort?view=netframework-4.8)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Threading/Thread.xml)
* Product: **dotnet-api**
* Technology: **system.threading**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@AFunnyKitty
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by AFunnyKitty** [comment]
https://docs.microsoft.com/zh-cn/dotnet/api/system.threading.thread.abort?view=netframework-4.8
此页面，文档中 “注解”节点 有描述：请注意，Thread.Abort在.NET Core 上不支持方法。
然后，此页面底部 “适用于”节点，显示：适用于 .NET Core 3.0 Preview 5 2.2 2.1 2.0
另外，实际在 .NETCore 代码中应用，编译时 会提示 .NET Core 不支持此方法
