### ISSUE TITLE
中文注解部分对时钟周期的描述错误

### ISSUE THREAD

**Issue by rikyoo** [dotnet/dotnet-api-docs.zh-cn#33]
原文"一个时钟周期表示 100 个纳秒的一千万分之一。"

应该是 一个时钟周期表示100个纳秒 或者 1秒的一千万分之一

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 82d96499-84b1-8ffd-1005-31a2e831c741
* Version Independent ID: db0484bb-939a-821d-a2b6-53f03a4108cf
* Content: [DateTime.Ticks Property (System)](https://docs.microsoft.com/zh-cn/dotnet/api/system.datetime.ticks?redirectedfrom=MSDN&view=netframework-4.8#feedback)
* Content Source: [xml/System/DateTime.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System/DateTime.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@rikyoo

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/dotnet-api-docs.zh-cn/pull/34 。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
