### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by Jassiner** [dotnet/dotnet-api-docs.zh-cn#35]
very nice

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 08638317-2f07-6fe0-f400-91f4ebc229ec
* Version Independent ID: 023ae21f-cbbb-71bf-2d2b-f18e86372b0d
* Content: [System.Net.Sockets Namespace](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.sockets?redirectedfrom=MSDN&view=netframework-4.0#feedback)
* Content Source: [xml/ns-System.Net.Sockets.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/ns-System.Net.Sockets.xml)
* Product: **dotnet-api**
* Technology: **system.net**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Hello, @Jassiner 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
