### ISSUE TITLE
翻译语序错误

### ISSUE THREAD

**Issue by Kucashu** [dotnet/dotnet-api-docs.zh-cn#36]
中文版本中(NotInheritable在 Visual Basic 中)的翻译应该为（在 Visual Basic 中为 NotInheritable）

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6ccb268f-7e61-578a-9cd5-eff767facdd4
* Version Independent ID: 65050b7a-8b46-c78f-0570-5c73ee35dd58
* Content: [Object.Equals Method (System)](https://docs.microsoft.com/zh-cn/dotnet/api/system.object.equals?view=netcore-3.0#System_Object_Equals_System_Object_)
* Content Source: [xml/System/Object.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System/Object.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@Kucashu
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Kucashu
感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/api/system.object.equals?view=netcore-3.0#System_Object_Equals_System_Object_

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
