### ISSUE TITLE
pipeServer.ReadMode赋值错误

### ISSUE THREAD

**Issue by ummpython** [dotnet/dotnet-api-docs.zh-cn#37]
匿名管道pipeServer.ReadMode不支持PipeTransmissionMode.Message

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4d376d7d-5bb0-d010-4584-b26913b9aa8c
* Version Independent ID: 58a4e996-64f1-9a4b-c334-34ae523dc029
* Content: [AnonymousPipeServerStream Class (System.IO.Pipes)](https://docs.microsoft.com/zh-cn/dotnet/api/system.io.pipes.anonymouspipeserverstream?view=netframework-4.5.2)
* Content Source: [xml/System.IO.Pipes/AnonymousPipeServerStream.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.IO.Pipes/AnonymousPipeServerStream.xml)
* Product: **dotnet-api**
* Technology: **system.io**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2650](https://github.com/dotnet/dotnet-api-docs/issues/2650) via [**ZenHub**](https://www.zenhub.com/)
