### ISSUE TITLE
What paramater should I pass to RSA.Create(string algName) ?

### ISSUE THREAD

**Issue by GreatFireWall** [dotnet/dotnet-api-docs.zh-cn#38]
Any docs for listing possible params ?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 71340042-8bc6-0269-8d17-914a651a4621
* Version Independent ID: 7186e4f1-9e1e-08b3-88c0-ee6c99ccf0d9
* Content: [RSA.Create Method (System.Security.Cryptography)](https://docs.microsoft.com/zh-cn/dotnet/api/system.security.cryptography.rsa.create?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1&view=netframework-4.8)
* Content Source: [xml/System.Security.Cryptography/RSA.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Security.Cryptography/RSA.xml)
* Product: **dotnet-api**
* Technology: **system.security**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by lichasu** [comment]
Hello, @GreatFireWall ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
