### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by LeeeAlpha** [dotnet/dotnet-api-docs.zh-cn#39]
The meaning of 'any' should be some, not all.
but the meaning of 'any' seems like all in chinese translation.
'都' means every element

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 028e83ab-7469-5a49-eb1e-fc733696bea3
* Version Independent ID: cbb14d50-ba7f-7f29-9535-43b936744bc4
* Content: [Enumerable.Any Method (System.Linq)](https://docs.microsoft.com/zh-cn/dotnet/api/system.linq.enumerable.any?view=netframework-4.8#feedback)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* Technology: **system.linq**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LeeeAlpha** [comment]
任何 = every element = all
存在 = have some

**Comment by srvbpigh** [comment]
Hello, @LeeeAlpha
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @LeeeAlpha
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/api/system.linq.enumerable.any?view=netframework-4.8

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
