### ISSUE TITLE
BOM被翻译成物料清单

### ISSUE THREAD

**Issue by Ivony** [dotnet/dotnet-api-docs.zh-cn#4]
好歹人工看一眼文档吧……

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7286f52a-0d12-166d-85ea-aa273cfab1b5
* Version Independent ID: 20e60442-25e0-53c2-bd44-42d8218a4e64
* Content: [UTF8Encoding Class (System.Text)](https://docs.microsoft.com/zh-cn/dotnet/api/system.text.utf8encoding?view=netframework-4.7.2)
* Content Source: [xml/System.Text/UTF8Encoding.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Text/UTF8Encoding.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
惊现大神。我来修一下吧_(:з」∠)_

**Comment by LisandroSu** [comment]
你好，@Ivony

感谢你的反馈。有问题的页面是采用机器翻译的，因此不一定容易理解。我们最近在右侧添加了“阅读英文版”选项，无需更改语言设置即可切换到的英文版。 


深深的祝福， 
Microsoft DOCS International Team
