### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by zhongxiwang** [dotnet/dotnet-api-docs.zh-cn#40]
在dotnet core 2.2中不能正确运行提供的示例,AssemblyBuilderAccess.RunAndSave是接口中是不存在的,AssemblyBuilder的Save方法也是不存在的,我应该怎么处理.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0bb23f8e-8486-c283-d2e9-e3f31c9e05d7
* Version Independent ID: ed0d8c0f-b04d-9cec-b47e-50d2d9724ab5
* Content: [AssemblyBuilder Class (System.Reflection.Emit)](https://docs.microsoft.com/zh-cn/dotnet/api/system.reflection.emit.assemblybuilder?view=netcore-2.2#feedback)
* Content Source: [xml/System.Reflection.Emit/AssemblyBuilder.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Reflection.Emit/AssemblyBuilder.xml)
* Product: **dotnet-api**
* Technology: **system.reflection**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
用Framework呗

**Comment by srvbpigh** [comment]
Hello, @zhongxiwang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@zhongxiwang 
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
