### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by LeeeAlpha** [dotnet/dotnet-api-docs.zh-cn#41]
Does Microsoft have no employees?
If you don't solve my problem, I will always submit feedback.
Chinese translation will mislead some people.
All "任何元素是否都" on this page should be changed to "是否有任意一个元素"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 028e83ab-7469-5a49-eb1e-fc733696bea3
* Version Independent ID: cbb14d50-ba7f-7f29-9535-43b936744bc4
* Content: [Enumerable.Any Method (System.Linq)](https://docs.microsoft.com/zh-cn/dotnet/api/system.linq.enumerable.any?view=netframework-4.8#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* Technology: **system.linq**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback! A member of our localization team will soon contact you. But you can also submit changes when you see issues. For more information, see https://docs.microsoft.com/zh-cn/contribute/#quick-edits-to-existing-documents

**Comment by srvbpigh** [comment]
Hello, @LeeeAlpha
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @LeeeAlpha
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/api/system.linq.enumerable.any?view=netframework-4.8#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__ 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
