### ISSUE TITLE
这个类有问题

### ISSUE THREAD

**Issue by nczsl** [dotnet/dotnet-api-docs.zh-cn#43]
X 这个字段，序列化不出来，
代码如下：
            DSAParameters dsap;            
            dsap.Counter = 32;
            dsap.Seed = new byte[] { 11, 12, 13 };
            dsap.P = new byte[] { 11, 12, 13 ,14,15};
            dsap.G = new byte[] { 21, 22, 23,24,22,25 };
            dsap.Q = new byte[] { 11, 12, 13,0,0 };
            dsap.J = new byte[] { 11, 12, 13 ,5}; //null;
            dsap.Y = new byte[] { 11, 12, 13,35,35,36,37,101 };
            dsap.X = new byte[] { 11, 12, 13 };
            var dsapstr=JsonConvert.SerializeObject(dsap);
            Console.WriteLine(dsapstr);
//
{"P":"CwwNDg8=","Q":"CwwNAAA=","G":"FRYXGBYZ","Y":"CwwNIyMkJWU=","J":"CwwNBQ==","Seed":"CwwN","Counter":32}

使用 vs2019 16.2.0 测试的

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 05010d73-0f0c-4c0f-456f-30e1180791c7
* Version Independent ID: 10155d1f-2434-46c7-4ba0-0a3f94d1c245
* Content: [DSAParameters Struct (System.Security.Cryptography)](https://docs.microsoft.com/zh-cn/dotnet/api/system.security.cryptography.dsaparameters?view=netframework-4.7.2&viewFallbackFrom=netstandard-1.2)
* Content Source: [xml/System.Security.Cryptography/DSAParameters.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Security.Cryptography/DSAParameters.xml)
* Product: **dotnet-api**
* Technology: **system.security**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @nczsl
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@nczsl
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
It's by designed.

```c#
// DSAParameters is serializable so that one could pass the public parameters
// across a remote call, but we explicitly make the private key X non-serializable
// so you cannot accidently send it along with the public parameters.
[Serializable]
[System.Runtime.InteropServices.ComVisible(true)]
public struct DSAParameters {
    public byte[]      P;
    public byte[]      Q;
    public byte[]      G;
    public byte[]      Y;
    public byte[]      J;
    [NonSerialized] public byte[]      X;
    public byte[]      Seed;
    public int         Counter;
}
```

**Comment by nczsl** [comment]
> It's by designed.
> 
> https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/dsa.cs
> 
> ```cs
> // DSAParameters is serializable so that one could pass the public parameters
> // across a remote call, but we explicitly make the private key X non-serializable
> // so you cannot accidently send it along with the public parameters.
> [Serializable]
> [System.Runtime.InteropServices.ComVisible(true)]
> public struct DSAParameters {
>     public byte[]      P;
>     public byte[]      Q;
>     public byte[]      G;
>     public byte[]      Y;
>     public byte[]      J;
>     [NonSerialized] public byte[]      X;
>     public byte[]      Seed;
>     public int         Counter;
> }
> ```

thank you !
