### ISSUE TITLE
asp.net core 2.2 提示 System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by jiaguoxinzhi** [dotnet/dotnet-api-docs.zh-cn#44]
System.PlatformNotSupportedException:“Operation is not supported on this platform.”
是什么原因

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 830d031d-082f-d93e-59ee-7d36c3aec6ba
* Version Independent ID: cf115b7a-6781-98fe-8422-9098e5ed5752
* Content: [CodeDomProvider.GenerateCodeFromCompileUnit(CodeCompileUnit, TextWriter, CodeGeneratorOptions) Method (System.CodeDom.Compiler)](https://docs.microsoft.com/zh-cn/dotnet/api/system.codedom.compiler.codedomprovider.generatecodefromcompileunit?view=netcore-2.2#feedback)
* Content Source: [xml/System.CodeDom.Compiler/CodeDomProvider.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.CodeDom.Compiler/CodeDomProvider.xml)
* Product: **dotnet-api**
* Technology: **system.codedom**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @jiaguoxinzhi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@jiaguoxinzhi
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
