### ISSUE TITLE
The ResourceManager.GetObject() In Linux

### ISSUE THREAD

**Issue by AlexRen01** [dotnet/dotnet-api-docs.zh-cn#45]
I execute the same ResourceManager. ResourceManager () method on Windows and Linux environments. Then get byte [] on windows, but on Linux can only get the string ”Linux x64 libindigo. so; System. Byte [], mscorlib, Version = 2.0.0.0, Culture = neutral, PublicKeyToken = b77a5c564e089”. What's the problem?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8f283464-c4a2-a9f0-de5b-964b97379b9b
* Version Independent ID: 3c46d853-777c-a0c4-f946-44752d8468e8
* Content: [ResourceManager.GetObject Method (System.Resources)](https://docs.microsoft.com/zh-cn/dotnet/api/system.resources.resourcemanager.getobject?view=netcore-3.0#feedback)
* Content Source: [xml/System.Resources/ResourceManager.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Resources/ResourceManager.xml)
* Product: **dotnet-api**
* Technology: **system.resources**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @AlexRen01
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @AlexRen01

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
