### ISSUE TITLE
请提供新式用法的示例！

### ISSUE THREAD

**Issue by KleinPan** [dotnet/dotnet-api-docs.zh-cn#47]
如题，最好有C++代码和C#代码互相调用的例子

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fefda702-61b2-2765-5629-74777733d8be
* Version Independent ID: 8149739c-0187-da29-a07e-3d53221447fa
* Content: [Marshal.PtrToStructure Method (System.Runtime.InteropServices)](https://docs.microsoft.com/zh-cn/dotnet/api/system.runtime.interopservices.marshal.ptrtostructure?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(System.Runtime.InteropServices.Marshal.PtrToStructure)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.8#feedback)
* Content Source: [xml/System.Runtime.InteropServices/Marshal.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Runtime.InteropServices/Marshal.xml)
* Product: **dotnet-api**
* Technology: **system.runtime**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @KleinPan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #3063](https://github.com/dotnet/dotnet-api-docs/issues/3063) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@KleinPan

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/dotnet-api-docs/issues/3063

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
