### ISSUE TITLE
Translation errors：The comment for field "AwayFromZero" was incorrectly translated into Chinese

### ISSUE THREAD

**Issue by jskenson** [dotnet/dotnet-api-docs.zh-cn#48]
The "小" should be the "大".like:当一个数字是其他两个数字的中间值时，会将其舍入为两个值中绝对值较大的值。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4c4d2ad3-0289-dab8-1101-1b6cf1f21b65
* Version Independent ID: 132f13b8-744c-c6cf-302d-c4ac83228f69
* Content: [MidpointRounding Enum (System)](https://docs.microsoft.com/zh-cn/dotnet/api/system.midpointrounding?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(System.MidpointRounding)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.8#feedback)
* Content Source: [xml/System/MidpointRounding.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System/MidpointRounding.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @jskenson
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jskenson 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/api/system.midpointrounding?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(System.MidpointRounding)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.8#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
