### ISSUE TITLE
注解第二段拼写错误

### ISSUE THREAD

**Issue by hanrai** [dotnet/dotnet-api-docs.zh-cn#49]
原文：
 您可以将MarshalAsAttribute特性应用于单个字段或参数, 以使该特定字符串LPStr作为而不BStr是封送。
修改为：
 您可以将MarshalAsAttribute特性应用于单个字段或参数, 以使该特定字符串作为LPStr而不是BStr封送。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 39dc33a8-ac20-b068-5ed1-bbd5bf72f1d2
* Version Independent ID: 4ab2c64c-615b-d1bf-b109-631d43ced41e
* Content: [MarshalAsAttribute Class (System.Runtime.InteropServices)](https://docs.microsoft.com/zh-cn/dotnet/api/system.runtime.interopservices.marshalasattribute?view=netframework-4.8)
* Content Source: [xml/System.Runtime.InteropServices/MarshalAsAttribute.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Runtime.InteropServices/MarshalAsAttribute.xml)
* Product: **dotnet-api**
* Technology: **system.runtime**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @hanrai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
