### ISSUE TITLE
示例小节翻译不准确

### ISSUE THREAD

**Issue by hanrai** [dotnet/dotnet-api-docs.zh-cn#50]
重新翻译如下：
在某些情况下, Visual Basic 开发人员使用DllImportAttribute代替Declare语句在托管代码中定义 DLL 函数。 设置CallingConvention字段便是这其中的一种情况。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 52200a65-8a19-9fe9-6efe-ab0c98915e77
* Version Independent ID: 58ef91a9-bc63-9c6e-7a13-08efe935590c
* Content: [DllImportAttribute.CallingConvention Field (System.Runtime.InteropServices)](https://docs.microsoft.com/zh-cn/dotnet/api/system.runtime.interopservices.dllimportattribute.callingconvention?view=netframework-4.8)
* Content Source: [xml/System.Runtime.InteropServices/DllImportAttribute.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Runtime.InteropServices/DllImportAttribute.xml)
* Product: **dotnet-api**
* Technology: **system.runtime**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @hanrai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
