### ISSUE TITLE
`loc-release` becomes default branch?

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/dotnet-api-docs.zh-cn#53]
`loc-release` becomes default branch. Is this expected?

**Comment by srvbpigh** [comment]
Hello, @imba-tjd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
can you please check this issue.
thanks in advance

**Comment by JasonCard** [comment]
Hi @imba-tjd, cc @CeciAC
Thank you for checking. This was not expected, so I've fixed the default branch back to `live` for all localized repos.
