### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/dotnet-api-docs.zh-cn#56]
https://docs.microsoft.com/zh-cn/dotnet/api/system.string

![图片](https://user-images.githubusercontent.com/24759802/67875185-fb262200-fb70-11e9-95a5-14cb9abc7214.png)

![图片](https://user-images.githubusercontent.com/24759802/67875453-53f5ba80-fb71-11e9-8fc3-e4d2857e86fd.png)

`Operators` should be `运算符`

`Explicit Interface Implementations` should be `显式接口实现`

Besides, the `language-toggle` is disappeared.

![图片](https://user-images.githubusercontent.com/24759802/67875697-b2bb3400-fb71-11e9-9668-2a1132fe8f5a.png)

**Comment by srvbpigh** [comment]
Hello, @imba-tjd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
I'm working on the linguistic part of this issue, but please kindly check the technical issue in last line:

"The language-toggle is disappeared."
![imagen](https://user-images.githubusercontent.com/26746247/67894213-de6cf880-fb36-11e9-8b7a-90c44728c142.png)

It replicates in other locales, too

**Comment by JasonCard** [comment]
Hi @imba-tjd, @CeciAc, 
The English toggle feature has been temporarily turned off for .NET API Browser as this feature was not properly supported for that content. We plan to have it turn on again after the feature is fully supported for .NET API Browser.

**Comment by CeciAc** [comment]
Hello, @imba-tjd 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team
