### ISSUE TITLE
title

### ISSUE THREAD

**Issue by enthural** [dotnet/dotnet-api-docs.zh-cn#6]
代码很好，基本上没有错误；但希望可以提供图片，因为对于项目开发者来说，不知道哪个组建具体是什么作用？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2a6f2a2c-bb7c-5d2e-bf51-7fe1ddb0ef43
* Version Independent ID: 0a4e1a1a-efc3-b44a-ef83-fd3304a042f0
* Content: [RichTextBoxStreamType Enum (System.Windows.Forms)](https://docs.microsoft.com/zh-cn/dotnet/api/system.windows.forms.richtextboxstreamtype?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/RichTextBoxStreamType.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Windows.Forms/RichTextBoxStreamType.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #8991](https://github.com/dotnet/docs/issues/8991) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@enthural

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/8991。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
