### ISSUE TITLE
翻译的语法问题太多，难以理解，句子太不通顺了！（very bad translation ）

### ISSUE THREAD

**Issue by luikaseng0722** [dotnet/dotnet-api-docs.zh-cn#8]
你好microsoft。这是我第一封写给你们的email。我正在学习c#，而且常常上来看，的确你们的网站帮我很多，我的英文也不好，所以常常需要看中文版，可是中文版的问题真的太多，语法的问题，常常让我不知道你们想要表达一些什么意思。能看出来几乎都是用google translation 差不多的软件来翻译吧。如果可以，建议你们用人出慢慢翻译，或者升级一下翻译软件，因为真的是太差了。too bad.看你们的中文网页，让我明白了，学好英文是多么重要！！。
我想要不你们改善一下中文网页的翻译，要么我学好英文！
  （”The Finalize method might not run to completion or might not run at all under the following exceptional circumstances:“
Finalize方法可能无法运行完成，或可能根本无法运行以下例外情况：
（应该是Finalize方法可能无法正常完成运行，或者可能在以下例外情况中根本无法运行）

If another finalizer blocks indefinitely (goes into an infinite loop, tries to obtain a lock it can never obtain, and so on). Because the runtime tries to run finalizers to completion, other finalizers might not be called if a finalizer blocks indefinitely.
如果另一个终结器会无限期阻止 （进入无限循环，尝试获取的锁，它可以永远不会获取，等等）。 由于运行时尝试运行终结器来完成，其他可能不调用终结器是如果终结器块无限期。
（应该是：当一个终结器会遇到死循环。（进入死循环，无法完成，等等）由于正在运行的终结器没法完成所以其他的终结器无法被调用。）

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b0bd11e3-6270-b53b-2959-b01dfcf4d799
* Version Independent ID: ba555604-699f-45cf-4b68-c2d69df809e9
* Content: [Object.Finalize Method (System)](https://docs.microsoft.com/zh-cn/dotnet/api/system.object.finalize?view=netframework-4.7.2#System_Object_Finalize)
* Content Source: [xml/System/Object.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System/Object.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@luikaseng0722
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@luikaseng0722

感谢你的反馈。有问题的页面是采用机器翻译的，因此不一定容易理解。我们最近在右侧添加了“阅读英文版”选项，无需更改语言设置即可切换到的英文版。 


深深的祝福， 
Microsoft DOCS International Team

@JasonCard fyi
